### ISSUE TITLE
Compile TF Ops errors

### ISSUE THREAD

**Issue by chdjianfeng** [intel-isl/Open3D-PointNet2-Semantic3D#25]
Hello. When I Compile TF Ops some errors occurred. How to solve it? This is the errors below.

```
-- The CXX compiler identification is GNU 7.3.0
-- The CUDA compiler identification is NVIDIA 9.2.148
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /content/Open3D-PointNet2-Semantic3D/tf_ops/build/open3d_root
Scanning dependencies of target open3d
[ 12%] Creating directories for 'open3d'
[ 25%] Performing download step (git clone) for 'open3d'
Cloning into 'open3d'...
Note: checking out '33e46f7'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 33e46f7d Merge pull request #729 from XuChengHUST/master
Submodule '3rdparty' (https://github.com/IntelVCL/Open3D-3rdparty) registered for path '3rdparty'
Cloning into '/content/Open3D-PointNet2-Semantic3D/tf_ops/build/open3d_root/open3d/src/open3d/3rdparty'...
Submodule path '3rdparty': checked out 'b08bff7856398f3bbd66e2b10a6f32e943e4ae34'
[ 37%] No update step for 'open3d'
[ 50%] No patch step for 'open3d'
[ 62%] Performing configure step for 'open3d'
-- The C compiler identification is unknown
-- The CXX compiler identification is GNU 7.3.0
CMake Error at CMakeLists.txt:22 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring incomplete, errors occurred!
See also "/content/Open3D-PointNet2-Semantic3D/tf_ops/build/open3d_root/open3d/src/open3d-build/CMakeFiles/CMakeOutput.log".
See also "/content/Open3D-PointNet2-Semantic3D/tf_ops/build/open3d_root/open3d/src/open3d-build/CMakeFiles/CMakeError.log".
CMakeFiles/open3d.dir/build.make:106: recipe for target 'open3d/src/open3d-stamp/open3d-configure' failed
make[2]: *** [open3d/src/open3d-stamp/open3d-configure] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/open3d.dir/all' failed
make[1]: *** [CMakeFiles/open3d.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
-- Could NOT find Open3D (missing: Open3D_DIR)
CMake Error at open3d.cmake:41 (message):
  Open3D build was not successful
Call Stack (most recent call first):
  open3d.cmake:45 (build_open3d)
  CMakeLists.txt:10 (include)


-- Configuring incomplete, errors occurred!
See also "/content/Open3D-PointNet2-Semantic3D/tf_ops/build/CMakeFiles/CMakeOutput.log".
```

**Comment by yxlao** [comment]
@chdjianfeng Looks like the C compiler cannot be found, but C++ compliler was found. 

First we can try to locate `gcc`, e.g. by
```bash
which gcc
gcc --version
```

If you're using `ccache`, you might also try
```bash
echo $CC
```

If gcc is not installed, install it, e.g.
```
sudo apt install gcc-7 # since you're using g++-7
```

If it still doesn't work, try to specify the compiler location explicitly when running cmake, e.g.
```bash
cmake -DCMAKE_C_COMPILER=/usr/bin/gcc ..
```

**Comment by amiltonwong** [comment]
Hi @yxlao ,
I got the same error `No CMAKE_C_COMPILER` when inputting command `cmake ..`. It's a bit strange as I did not encounter such error when performing cmake step for other c++ project . Is something special when [calling ](https://github.com/IntelVCL/Open3D-PointNet2-Semantic3D/blob/master/tf_ops/CMakeLists.txt#L10) [open3d. cmake](https://github.com/IntelVCL/Open3D-PointNet2-Semantic3D/blob/master/tf_ops/open3d.cmake)?

BTW, I build it successfully after using `cmake -DCMAKE_C_COMPILER=/usr/bin/gcc ..`

**Comment by zcyy-lushijie** [comment]
it works！！

**Comment by sarraghd** [comment]
@yxlao  Hi sir thnak you for the great work, i using bash on ubuntu on windows, I got the error No CMAKE_CUDA_COMPILER could be found.
I tried /mnt/d/Open3D-PointNet2-Semantic3D-master/tf_ops/build$ cmake -DCUDA_TOOLKIT_ROOT_DIR="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0"..
But I am getting This CMake Error: The source directory "/mnt/d/Open3D-PointNet2-Semantic3D-master/tf_ops/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Any solution for this?

**Comment by changhexingchen** [comment]
This error still does exist even when I input cmake -DCMAKE_C_COMPILER=/usr/bin/gcc ..

**Comment by changhexingchen** [comment]
@chdjianfeng Have you solved that problem? Thanks.

**Comment by zcyy-lushijie** [comment]
yes ,it works when i changed the C compiler path and C++ compiler path

> @chdjianfeng Have you solved that problem? Thanks.

**Comment by changhexingchen** [comment]
@zcyy-lushijie  Could you tell me which file did you modify? Thank you!

**Comment by zcyy-lushijie** [comment]
when i run the script
cd tf_ops mkdir build cd build cmake .. makei changed "cmake.." to "cmake -DCMAKE_C_COMPILER=/usr/bin/gcc .."




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"qcc"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月25日(星期一) 下午2:56
收件人:&nbsp;"intel-isl/Open3D-PointNet2-Semantic3D"<Open3D-PointNet2-Semantic3D@noreply.github.com&gt;;
抄送:&nbsp;"1170693751"<1170693751@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [intel-isl/Open3D-PointNet2-Semantic3D] Compile TF Ops errors (#25)




@zcyy-lushijie  Could you tell me which file did you modify? Thank you!

**Comment by phulektqs** [comment]
> @chdjianfeng Have you solved that problem? Thanks.


I also have the same case. Have you solved it?
