### ISSUE TITLE
missing: Tensorflow framework library

### ISSUE THREAD

**Issue by tiger-bug** [intel-isl/Open3D-PointNet2-Semantic3D#52]
Good morning,

I am on step 4 **(Compile TF_OPS)** and ran into an error.  The message states:   Could NOT find TensorFlow (missing: TensorFlow_FRAMEWORK_LIBRARY) 

I installed tensorflow via pip.  Is that the incorrect way to do it?  I am running Ubuntu 18.04.  Attached is a screenshot of the error.  Thank you so much!

![open3d_error](https://user-images.githubusercontent.com/40045042/60815885-274f0a80-a15e-11e9-9c3f-812af8447003.png)

**Comment by sarraghd** [comment]
Hi, Iam on step 3 trying to downsample the data did you get this problem

![Capture](https://user-images.githubusercontent.com/50463007/61316204-72a49100-a7ce-11e9-847a-cc76e312663e.PNG)

**Comment by f3rhoodn** [comment]
@spiegelss did you solve this problem? I got exactly the same problem.

**Comment by Naor92** [comment]
Also getting this same issue with Pip install of Tensorflow.

**Comment by f3rhoodn** [comment]
@Naor92 fixed this issue by installing tensorflow 1.12

**Comment by Naor92** [comment]
@f3rhoodn seems like ‘pip uninstall tensorflow-estimator’ is what did it for me oddly enough

**Comment by spiegelss** [comment]
Sorry everyone I've been a bad githubber and have not followed up as I should.  I will attempt  with tensorflow 1.12.  As far as sarrghd's, error, I did not get that and unfortunately do not know why you are.  I can look into it though!  I will report back as soon as I figure it out.  Thanks everyone!

**Comment by tcosculluela** [comment]
@spiegelss I managed to "fix" this on 1.14, after trying to set the missing variable through command-line args I just installed cmake-gui. After running 'cmake-gui ..' , I filled in the problematic TensorFlow_FRAMEWORK_LIBRARY variable with "-TENSORFLOW_FRAMEWORK_LIBRARY=/home/whatever/anaconda3/envs/whatever/lib/python3.6/site-packages/tensorflow"

After that all I had to do was symlink the libtensorflow_framework.so file to /usr/lib so the makefile could compile

So now I have the tf_ops, but they segfault when running test_tf_ops.py

**Comment by vcfrasineanu** [comment]
@tcosculluela I have the same problem when I try to run the tf_ops. Did you manage to fix the segfaults?

**Comment by tcosculluela** [comment]
@vcfrasineanu I haven't tried yet, but I imagine it has something to do with TF/cuda/python versions. I'm going to try with Cuda 9.0 and an earlier version of TF

Currently I'm using Cuda 10.1 and TF 1.14

**Comment by sarraghd** [comment]
@tcosculluela did you manage to produce the .so files?

**Comment by stephansturges** [comment]
Did anyone find a solution to this?  I'm completely stuck on this installation step and can't figure anything out :-(

**Comment by Tojens** [comment]
I'm also hoping someone can go into a bit more depth on how to solve this issue

**Comment by Monikake** [comment]
It got  solved for  tensorflow-1.13.0rc1(tensorboard-1.12.2)

**Comment by ManuelZ** [comment]
@Monikake I can confirm that by installing tensorflow-gpu v1.13.2 I was able to complete the compilation.
Haven't tried running it though.

**Comment by monroe-dev** [comment]
@tcosculluela Did you solve the problem? Do I need to make a virtual env? I just use a pip install method, but it cannot determine TensorFlow installation directory.

- Ubuntu/Python: 18.04/3.6.9

- Tensorflow: 1.13.1 (but I also try 1.14)

- CUDA: 10.0

- numpy: 1.17.4

![tensor_error](https://user-images.githubusercontent.com/60613058/74029510-2a5df200-49f0-11ea-8fff-52652e34a89b.png)

**Comment by hujinhan12** [comment]
> @spiegelss I managed to "fix" this on 1.14, after trying to set the missing variable through command-line args I just installed cmake-gui. After running 'cmake-gui ..' , I filled in the problematic TensorFlow_FRAMEWORK_LIBRARY variable with "-TENSORFLOW_FRAMEWORK_LIBRARY=/home/whatever/anaconda3/envs/whatever/lib/python3.6/site-packages/tensorflow"
> 
> After that all I had to do was symlink the libtensorflow_framework.so file to /usr/lib so the makefile could compile
> 
> So now I have the tf_ops, but they segfault when running test_tf_ops.py

This works. I tested on jetson tx2 with tensorflow 1.15

**Comment by tiger-bug** [comment]
Hello everyone.  I realize it's been a while and I've come back to this, but here was my solution.  Instead of building it on my machine I used a tensorflow docker image from [nvidia](https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes/rel_19.01.html#rel_19.01).  Now, as suggested by  @f3rhoodn, this is a TF 1.12 version.  Here is a copy of my dockerfile

```
FROM nvcr.io/nvidia/tensorflow:19.01-py3
ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
  RUN apt-get update && apt-get install -f -y \
  git \
  xorg-dev \
  libglu1-mesa-dev
#   cmake 
RUN wget https://github.com/Kitware/CMake/releases/download/v3.13.4/cmake-3.13.4.tar.gz # get latest version of cmake 
RUN tar -zxvf /workspace/cmake-3.13.4.tar.gz
WORKDIR /workspace/cmake-3.13.4
RUN bash bootstrap
RUN make
RUN make install
RUN pip install \
##install plyfile is not necessary, but I need it for my purposes
 plyfile \
 open3d

```

I hope this helps.

**Comment by sohamchoudhary** [comment]
Try doing it with a conda environment with tensorflow-gpu=1.13
